In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Günlük Çalışma

In [44]:
df=sns.load_dataset("mpg")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [45]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [47]:
df["origin"].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [48]:
# origin sütunudaki kategorik değerleri label encodig ile sayısal hale getirme. (Az kategori olduğndan label Encodign seçtim ama one-hot Encoding' de yapılabilir)

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['origin'] = encoder.fit_transform(df['origin'])

In [49]:
df["origin"].unique()

array([2, 1, 0])

In [50]:
df[df["name"]=="chevrolet impala"][["name","horsepower"]]

                 name  horsepower
6    chevrolet impala       220.0
38   chevrolet impala       165.0
62   chevrolet impala       165.0
103  chevrolet impala       150.0

In [51]:
df[df["horsepower"].isnull()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,2,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,2,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,0,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,2,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,0,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,2,amc concord dl

In [52]:
df = df.dropna(subset=["horsepower"])

In [53]:
df[df["horsepower"].isnull()] # nan değer kalmadı beygir gücü eksik olan değerler silindi.

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin, name]
Index: []

In [54]:
df2=sns.load_dataset("mpg")

In [55]:
df2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
# Aynı name'e sahip diğer araçların ortalama horsepower NaN'leri doldurmak

In [56]:
df2[df2["name"]=="ford pinto"]  # daha iyi anlamak için eksik olan tek nan değeri diğer ford pinto araçların beygir ortalaması ile dolduralacak

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto

In [ ]:
# nan olan satırları döngüyle gez
for i, row in df2[df2["horsepower"].isnull()].iterrows():
    car_name = row["name"]

    # Aynı isimdeki diğer araçların beygirlerini al (nan olmayanlar)
    same_model_hp = df2[(df2["name"] == car_name) & (df2["horsepower"].notnull())]["horsepower"]

    if not same_model_hp.empty:
        mean_hp = same_model_hp.mean()
        df2.at[i, "horsepower"] = mean_hp
    else:
        
        df2.at[i, "horsepower"] = df2["horsepower"].mean()

In [58]:
df2[df2["name"]=="ford pinto"]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,83.4,2046,19.0,71,usa,ford pinto
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto

In [59]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB